### ISSUE TITLE
Remove imports in __init__ for modules

### ISSUE THREAD

**Issue by Solpatium** [software-mansion/starknet.py#475] opened 2022-10-21 09:01 UTC
**Is your feature request related to a problem? Please describe.**
Importing files in __init__ can cause cyclic imports.

**Describe the solution you'd like**
Deprecate them and remove them after some time.

**Describe alternatives you've considered**
Leaving it as it is now.

**Additional context**
https://github.com/software-mansion/starknet.py/pull/471#discussion_r1000403597

**Comment by cptartur** [comment] 2022-11-07 09:13
Thing to consider: how to deprecate imports in `__init__.py` files.

**Comment by cptartur** [comment] 2022-11-21 08:25
Blocked until #376 is resolved

**Comment by cptartur** [comment] 2023-02-06 09:44
Duplicate of #562

**Closed by cptartur** 2023-02-06 09:44 UTC
Labels: enhancement, question, priority: low, refactor
