### ISSUE TITLE
[BUG] cannot verify a signature with cpp_verify

### ISSUE THREAD

**Issue by ClementWalter** [software-mansion/starknet.py#1507] opened 2024-10-08 08:58 UTC
### What happened

See

```
from starkware.crypto.signature.signature import private_to_stark_key, sign, verify

verify(
    msg_hash,
    *sign(msg_hash=msg_hash, priv_key=private_key),
    private_to_stark_key(private_key),
)
```

and

```
from crypto_cpp_py.cpp_bindings import cpp_get_public_key, cpp_sign, cpp_verify

cpp_verify(
    msg_hash,
    *cpp_sign(msg_hash, private_key),
    cpp_get_public_key(private_key),
)
```

### Stack trace

just run the code

### Steps to reproduce

just run the code

### SDK Version

0.23.0

### Python version

3.10.13

### What operating system are you using?

Mac

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by franciszekjob** [comment] 2024-10-10 10:22
Let's consider such data (generated_with `seed = 0`):
```python
msg_hash = 333
private_key = 1
sig = (2400113137211266340585990776105439108590051810022943045864222356533250780835,
           796598274585886909227299177867598639238949760716140634636805272055703633201)
```

Now let's verify it using `verify_message_signature` from starknet.py:
```python
print(verify_message_signature(
        msg_hash,
        sig,
        private_to_stark_key(private_key),
    ))
```
Result:
```python
True
```

Let's do the same with `verify` from cairo-lang:
```python
print(verify(
    msg_hash,
    *sign(msg_hash=msg_hash, priv_key=private_key),
    private_to_stark_key(private_key),
))
```

Result:
```python
True
```

So verify functions from both libs validate correctly. I don't really see what's the issue here. maybe this problem was caused by https://github.com/software-mansion/starknet.py/issues/1507? What do you exactly understand by "cannot verify a signature"?

**Comment by ClementWalter** [comment] 2024-10-10 10:39
<img width="702" alt="image" src="https://github.com/user-attachments/assets/6e51ad23-59fc-4262-91ab-4380758ce1e9">
fully working snippets with imports

**Comment by akintewe** [comment] 2024-10-10 15:38
Hello can i be assigned this task, i have an idea on how to tackle it

**Closed** 2024-10-18 13:39 UTC
Labels: bug
