### ISSUE TITLE
[BUG] Signature Generation Discrepancy between starknet.js and starknet_py

### ISSUE THREAD

**Issue by eugypalu** [software-mansion/starknet.py#1501] opened 2024-10-01 12:42 UTC
### What happened

I'm encountering an issue when comparing signatures generated by starknet.js and starknet_py. I've verified that both scripts generate the same transaction_hash, but despite this, the produced signatures are different.

1. Create two separate scripts, one in JavaScript using starknet.js and one in Python using starknet_py.
2. In both scripts, use the same private key (set the key in the env) and transaction parameters (hardcodded in the github script).
3. Verify that both scripts generate the same transaction_hash.
4. Generate the signature using `signTransaction` on starknet.js and `sign_invoke_v1` on starknet_py.
5. Compare the obtained signatures.

I've uploaded both scripts used for this test in this repository: [Github repo](https://github.com/eugypalu/starknet-signature-test)

### Current Result
Despite the same transaction_hash being generated in both scripts and the same private_key used for signing, the signatures produced by starknet.js and starknet_py are different.

### Expected Result
I would expect that, given the same transaction_hash and private key, both libraries would generate the same signature.

### Environment
- starknet_py version: 0.23.0
- starknet.js version: 6.11.0

### Support Request
Considering that the transaction_hash is identical in both scripts, is there any known difference in the signing process between starknet.js and starknet_py that could explain this discrepancy?
I appreciate any assistance or guidance on how to resolve this discrepancy. If additional information or details about my setup are needed, I'll be happy to provide them. The test scripts are available in the linked repository above for a more in-depth review. Thank you

### Stack trace

No error, the signatures do not match.
Despite the same transaction_hash being generated in both scripts and the same private_key used for signing, the signatures produced by starknet.js and starknet_py are different.

### Steps to reproduce

I've uploaded both scripts used for this test in this repository: [Github repo](https://github.com/eugypalu/starknet-signature-test)
There is a README in the repo with all the information to run both scripts.

## Steps to Reproduce
1. Create two separate scripts, one in JavaScript using starknet.js and one in Python using starknet_py.
2. In both scripts, use the same private key (set the key in the env) and transaction parameters (hardcodded in the github script).
3. Verify that both scripts generate the same transaction_hash.
4. Generate the signature using `signTransaction` on starknet.js and `sign_invoke_v1` on starknet_py.
5. Compare the obtained signatures.

### SDK Version

0.23.0

### Python version

3.10.14

### What operating system are you using?

Mac

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by franciszekjob** [comment] 2024-10-02 06:10
hey @eugypalu , thanks for report, will see handle it today and update you 👍 .

**Comment by franciszekjob** [comment] 2024-10-07 23:14
@eugypalu the discrepancy comes from different seed value in a function from `crypto_cpp_py`.
Seed in [this function](https://github.com/software-mansion-labs/crypto-cpp-py/blob/805bb4909d67ca725466d1fe04da5149d4bfee4e/crypto_cpp_py/cpp_bindings.py#L135) has a default value of 32, when in starknet.js it's 0. It looks like we maye have a small mistake, but I need to confirm it. Will update you on this.

**Comment by franciszekjob** [comment] 2024-10-10 09:49
Seed causes that signature is different, however it's still **correct** (it's checked by `cpp_verify`) and the discrepancy  between other SDKs and starknet.py is not a bug. Closing.

**Closed by franciszekjob** 2024-10-10 09:49 UTC
Labels: bug
